import Hippodrome from "./assets/nftPictures/Hippodrome.jpg";
import benHill from "./assets/nftPictures/benHillNight.jpg";
import downtownAtNight from "./assets/nftPictures/downtownAtNight.jpg";
import uf from "./assets/nftPictures/uf.jpg";
import reitz from "./assets/nftPictures/ReitzUnion.jpg";
import PaynePrarie from "./assets/nftPictures/PaynePrarie.jpg";
import HHall from "./assets/nftPictures/HHall.jpg";
import LakeAlice from "./assets/nftPictures/LakeAlice.jpg";
import FLoridaGator from "./assets/nftPictures/FloridaGator.jpg";
import DDen from "./assets/nftPictures/DDen.jpg";
// ShuttterStock
export const nfts = [
  {
    id: 1,
    title: "Gainesville Hippodrome",
    url: Hippodrome,
    originalPrice: 49.99,
    salePrice: 14.95,
    rating: 4.5,
    delivery: "Instant",
    releaseDate:"Soon!",
    duration: 1 * 16 * 43 * 60 * 1000,
    caption: "The Gainesville Hippodrome is a vibrant and dynamic performing arts center located in the heart of downtown Gainesville, Florida. With its historic and charming architecture, the Hippodrome offers a unique and intimate setting for a wide range of theatrical productions, film screenings, and other cultural events.",
  },
  {
    id: 2,
    title: "The Swamp",
    url: benHill,
    originalPrice: 39.25,
    salePrice: null,
    rating: 5,
    delivery: "Instant",
    releaseDate:"11/12/2022",
    duration: null,
    caption: `Ben Hill Griffin Stadium, also known as "The Swamp," is a legendary college football stadium and a beloved institution at the University of Florida. With a seating capacity of over 90,000 fans, The Swamp is one of the largest and most iconic venues in the country, and a truly unforgettable experience for anyone who attends a game.`,
  },
  {
    id: 3,
    title: "Downtown In the Evening",
    url: downtownAtNight,
    originalPrice: 29.88,
    salePrice: null,
    rating: 5,
    delivery: "Standard",
    releaseDate:"1/3/2023",
    duration: null,
    caption: "Downtown Gainesville, Florida is a vibrant and lively hub of culture, commerce, and entertainment. With its charming historic architecture, bustling shopping districts, and lively music and arts scene, the downtown area offers something for everyone. Visitors can explore a wide variety of unique shops, restaurants, and local businesses, as well as attend live performances, cultural festivals, and other community events.",
  },
  {
    id: 4,
    title: "UF Center",
    url: uf,
    originalPrice: 12.23,
    salePrice: 19,
    rating: 4.5,
    delivery: "Standard",
    releaseDate:"Soon!",
    duration: 5 * 6 * 40 * 60 * 1000,
    caption: "The University of Florida is a world-renowned academic institution and a beloved institution of higher education in the state of Florida. With its extensive academic programs, cutting-edge research facilities, and vibrant campus community, UF is a top-ranked university that attracts students, scholars, and researchers from all over the world.",
  },
  {
    id: 5,
    title: "UF Reitz Union",
    url: reitz,
    originalPrice: 27.75,
    salePrice: 14.95,
    rating: 5,
    releaseDate:"10/12/2022",
    duration: null,
    delivery: "Instant",
    caption:
      "The University of Florida Reitz Union is a vibrant and welcoming hub of student life on campus. With a wide range of facilities and resources, including restaurants, study areas, event spaces, and recreational activities, the Reitz Union provides a lively and engaging environment for students to connect, learn, and grow.",
  },
  {
    id: 6,
    title: "Paynes Prairie",
    url: PaynePrarie,
    originalPrice: 22.99,
    salePrice: null,
    rating: 5,
    duration: null,
    delivery: "Standard",
    releaseDate:"2/1/2023",
    caption: "Paynes Prairie Preserve State Park in Alachua, Florida is a natural wonderland of stunning beauty and ecological diversity. With over 21,000 acres of protected wilderness, the park is home to a variety of unique ecosystems, including freshwater marshes, pine flatwoods, and hardwood hammocks.",
  },
  {
    id: 7,
    title: "Heavener Hall",
    url: HHall,
    originalPrice: 71.44,
    salePrice: null,
    rating: 3,
    delivery: "Instant",
    releaseDate:"Soon!",
    duration: 9 * 24 * 60 * 60 * 1000,
    caption: "Heavener Hall at the University of Florida is a state-of-the-art academic facility that fosters a collaborative and dynamic learning environment for business students. With its innovative design and cutting-edge technology, Heavener Hall provides students with a range of advanced resources and learning tools, including modern classrooms, multimedia labs, and collaborative workspaces.",
  },
  {
    id: 8,
    title: "Lake Alice",
    url: LakeAlice,
    originalPrice: 8.45,
    salePrice: 19,
    releaseDate:"12/27/2022",
    delivery: "Standard",
    rating: 4.5,
    duration: null,
    caption: "Lake Alice is a serene and picturesque natural oasis nestled within the heart of Alachua County, Florida. With its tranquil waters, lush greenery, and abundant wildlife, Lake Alice offers a peaceful escape from the hustle and bustle of city life.",
  },
  {
    id: 9,
    title: "Florida Gator",
    url: FLoridaGator,
    originalPrice: 72.05,
    salePrice: null,
    rating: 5,
    releaseDate:"1/24/2023",
    duration: null,
    delivery: "Instant",
    caption:
      "The Florida Gator is an iconic symbol of strength, resilience, and determination. Representing the University of Florida's athletic teams, the Gator embodies the spirit of fierce competition and unwavering dedication.",
  },
  {
    id: 10,
    title: "Devils Den Sinkhole",
    url: DDen,
    originalPrice: 99.01,
    salePrice: 19,
    rating: 4.5,
    delivery: "Standard",
    releaseDate:"Soon!",
    duration: 1 * 4 * 44 * 60 * 1000,
    caption: "Devil's Den Sinkhole in Gainesville, Florida is a unique and awe-inspiring geological wonder. Located within a lush and vibrant natural setting, the sinkhole is an underground spring that offers visitors an opportunity to explore a stunning subterranean world of crystal-clear water and unique rock formations.",
  },
];
